<!DOCTYPE html>
<html>
<head>
	<title>Not found</title>
	<style>
		html, body {
			font-family: Helvetica, Sans Serif;
			background: #eee;
		}
		.error-container {
			text-align: center;
			margin: 6rem 0;
		}

		.error-container h1 {
			color: #444;
			font-weight: normal;
		}

		.error-container h1.for-ou-for {
			color: #bf5252;
			font-size: 60px;
		}

		.error-container h2 {
			color: #666;
			font-style: italic;
		}
	</style>
</head>
<body>
	<div class="error-container">
		<h1 class="for-ou-for">404</h1>
		<h1>You are looking to the wrong direction.</h1>
		<h2>It's not here.</h2>
	</div>
</body>
</html>