<!DOCTYPE html>
<html>
<head>
	<title>Not found</title>
	<style>
		html, body {
			font-family: Helvetica, Sans Serif;
			background: #eee;
		}
		.error-container {
			text-align: center;
			margin: 6rem 0;
		}

		.error-container h1 {
			color: #444;
			font-weight: normal;
		}

		.error-container h1.faiv-ou-ou {
			color: #7963bd;
			font-size: 60px;
		}

		.error-container h2 {
			color: #666;
			font-style: italic;
		}
	</style>
</head>
<body>
	<div class="error-container">
		<h1 class="faiv-ou-ou">500</h1>
		<h1>Somebody messed up.</h1>
		<h2>Pretend you didn't see that.</h2>
	</div>
</body>
</html>