<!DOCTYPE html>

<html lang="en">
	<head>
		<!-- Meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="author" content="Miika Sikala">
		<link rel="icon" type="image/jpeg" href="/favicon.jpg" />
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

		<!-- Styles -->
		<link rel="stylesheet" href="<?=assetVersion('/css/app.css');?>">

		<title>Rockets</title>

		<!-- TODO: use webpack! -->
		<script src="/js/plotly.min.js"></script>
	</head>
	<body>

		<!-- Top Nav -->
		<header class="navbar navbar-dark bg-dark flex-md-nowrap p-0 shadow justify-content-center">
			<a class="navbar-brand col-md-2 mr-0" href="/">Rockets</a>
		</header>
		
		<div class="nav-scroller py-1 mb-2">
			<nav class="nav d-flex justify-content-center">
				<a class="p-2 text-muted<?=(isset($vars['active-link']) && in_array($vars['active-link'], ['concepts/concepts', 'concepts/equations'])) ?' link-active':''?>" href="/concepts">Concepts</a>
				<a class="p-2 text-muted<?=(isset($vars['active-link']) && $vars['active-link'] == 'rockets') ?' link-active':''?>" href="/rockets">Rockets</a>
				<a class="p-2 text-muted<?=(isset($vars['active-link']) && $vars['active-link'] == 'related-theory') ?' link-active':''?>" href="/related-theory">Related Theory</a>
				<a class="p-2 text-muted<?=(isset($vars['active-link']) && $vars['active-link'] == 'links') ?' link-active':''?>" href="/links">Links</a>
			</nav>
		</div>

		<?=$contents['content'];?>

		<footer class="text-center mt-5 mb-3 text-muted">
			by Miika Sikala
		</footer>

		<!-- Scripts that load after DOM -->
		<script src="/js/app.js"></script>
	</body>
</html>
