<div class="container">

	<section class="mt-5">
		<h2>My Notes</h2>

		<p>I collect my notes and crazy ideas about this site here...</p>

		<h3>Things to show</h3>
		<ul>
			<li>Derivation of equations</li>
			<li>Minigames that visualize hard-to-understand or complex concepts</li>
			<li>Interactive graphs (i.e. change k-values and see how it affects I<sub>s</sub>)</li>
			<li>Catch-ups/references of main ideas/terms</li>
			<li>Connection to real-world solutions: "<i>Saturn V</i> had that amount of thrust in 1st stage", "This, this and this engine use this propellant", ...</li>
		</ul>

		<h3>Other</h3>
		<ul>
			<li>When hovering an equation (anywhere), show short description and what each variable/constant means, also links to related pages.</li>
			<li>Own page for each concept with thorough examples, graphs, illustrations and minigames...
		</ul>

	</section>

</div>
